Music Store (Practice 2019, .NET + DB)/music_store/music_store/Controllers/usersASPsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Security.Claims;
using System.Web;
using System.Web.Mvc;
using Microsoft.AspNet.Identity;
using Microsoft.Owin.Security;
using music_store.Models;

namespace music_store.Controllers
{
    public class UsersASPsController : Controller
    {
        private readonly music_storeEntities4 db = new music_storeEntities4();

        private void SignInUser(string username, bool isPersistent)
        {
            var claims = new List<Claim>();
            
            try
            {
                claims.Add(new Claim(ClaimTypes.Name, username));
                
                var claimIdenties = new ClaimsIdentity(claims, DefaultAuthenticationTypes.ApplicationCookie);
                var ctx = Request.GetOwinContext();

                var authenticationManager = ctx.Authentication;
                authenticationManager.SignIn(new AuthenticationProperties { IsPersistent = isPersistent },
                    claimIdenties);
            }
            catch (Exception ex)
            {
                throw ex;
            }
        }

        public ActionResult Signout()
        {
            var ctx = Request.GetOwinContext();
            
            var authenticationManager = ctx.Authentication;
            authenticationManager.SignOut();

            return RedirectToAction("Index", "Home");
        }
        
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Login([Bind(Include = "log_in, pass_word")] sellers model)
        {
            if (ModelState.IsValid)
            {
                var login = db.LoginByUsernamePassword(model.log_in, model.pass_word).ToList();
                
                if (login != null && login.Count > 0)
                {
                    var details = login.First();
                    SignInUser(details.log_in, false);
                    return RedirectToAction("Index", "Home");
                }
            }
            return View(model);
        }

        [AllowAnonymous]
        public ActionResult Login()
        {
            if (Request.IsAuthenticated)
                return RedirectToAction("Index", "Home");

            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult reg([Bind(Include = "log_in, pass_word, role")] sellers user)
        {
            if (ModelState.IsValid)
            {
                var insert = db.Insert_User(user.log_in, user.pass_word, user.role).ToList();
                if (insert != null && Convert.ToInt32(insert[0]) != -1)
                {
                    db.SaveChanges();
                    return RedirectToAction("Login", "usersASPs");
                }

                ViewBag.Error = "Пользователь с таким login уже существует";
                return View();
            }
            return View();
        }

        public ActionResult reg()
        {
            return View();
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing) db.Dispose();
            base.Dispose(disposing);
        }
    }
}

Music Store (Practice 2019, .NET + DB)/music_store/music_store/Views/usersASPs/Login.cshtml
@model music_store.Models.sellers

@{
    ViewBag.Title = "Login to us :)";
}

<h2>Login</h2>


@using (Html.BeginForm("Login", "UsersASPs", FormMethod.Post))
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <hr/>
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })

        <div class="form-group">
            @Html.LabelFor(model => model.log_in, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.log_in, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.log_in, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.pass_word, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.pass_word, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.pass_word, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default"/>
            </div>
        </div>
    </div>
}

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

Music Store (Practice 2019, .NET + DB)/music_store/music_store/Views/usersASPs/reg.cshtml
@{
    ViewBag.Title = "Регистрация";
}


<section class="content register">

    <form method="post">

        <input type="text" name="log_in" required placeholder="Логин">

        <input type="password" name="pass_word" required placeholder="Пароль">

        <input type="text" name="role" required placeholder="Роль">

        <button type="submit">Зарегистрироваться</button>

        <span class="error">@ViewBag.Error</span>

    </form>

</section>